
name: IMDBCatalog
options:
  deploymentTarget:
    iOS: 16.0

configs:
  debug: debug
  release: release

settings:
  base:
    DEVELOPMENT_TEAM: ZFFBJVL857
    CURRENT_PROJECT_VERSION: 1.0
    MARKETING_VERSION: 1.0
    PRODUCT_BUNDLE_IDENTIFIER: 'com.zup.imdbcatalog'
    debugEnabled: true
  debug:
    debugEnabled: true
  release:
    debugEnabled: false
  
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    version: 5.6.1

targets:
  IMDBCatalog:
    type: application
    platform: iOS
    sources: 
      - path: IMDBCatalog
    settings:
      INFOPLIST_FILE: info.plist
    dependencies:
      - package: Alamofire
schemes: 
    IMDBCatalogDebug:
      build:
        targets: 
          IMDBCatalog: all
      run: 
        config: debug
    IMDBCatalogRelease:
      build:
        targets: 
          IMDBCatalog: all
      run:
        config: release
parallelizeBuild: true
